- resources/lib/server_detect.py
- resources/settings.xml
Emby let you request more data than the Jellyfin API does. Brought the allowed options back in line with what our API allows. Fixes #5
> Lowered the maximum connection test size to comply with API limits

- resources/lib/downloadutils.py
- resources/lib/server_detect.py
- resources/settings.xml
Have put some migration code in for backwards comparability testing which appears to be doing okay. This fix will now default to using http and https default port as well as allow for baseurls to work properly
> Store full URL instead of component parts. Fixes #1 and Fixes #2

- resources/lib/websocket_client.py
Jellycon still had the old endpoint at `/websocket` configured which got moved to `/socket`.
This changes the endpoint to the current upstream and therefore fixes playback of transcoded streams among other things involving the socket.
> Fix websocket_url (fixes playing transcoded streams)

- resources/lib/menu_functions.py
Browsing to the `#` doesn't work, and I'm guessing special characters are right out, but fixes the standard alphabet.  Seems to be a bug with the server API.
> Fix browsing libraries by letter

- resources/lib/functions.py
Server changes in 10.6 means that sometimes the server returns `'None'` instead of `None`.  Because it hates us.  Catches that bit of fun and handles it
> Fix casting from web UI

- resources/lib/skin_cloner.py
Fixes #38 (mostly).  The skin isn't a 100% match, it seems to automatically hide the navigation on the left side.  I'm not sure if this was an intentional choice or not yet, but this at least makes the function work.
> Fix clone skin function

- resources/language/resource.language.en_gb/strings.po
- resources/lib/cache_images.py
- resources/lib/datamanager.py
- resources/lib/downloadutils.py
- resources/lib/server_detect.py
- resources/lib/trakttokodi.py
Some existing translations contain `%s` and are then replaced in the string when displayed to the user.  This is both ugly and a bad practice if/when we get localization set up, because that won't translate to other languages well.
> Stop doing string manipulations on translations

- resources/lib/downloadutils.py
- resources/lib/item_functions.py
Python 3 renamed the unicode type to str
> Change unicode to str

- resources/settings.xml
Assumed fix for #81 and #83 for future clean installs.  Disables the "Show user select on screensaver" and "Stop playback on screensaver" settings.
Also removes dead/commented out settings.
> Disable screensaver settings by default

- resources/lib/functions.py
- resources/lib/widgets.py
Many widgets indicate they only show 20 items, but this was inaccurate and was causing some widgets to be populated with hundreds of items
> Make API calls respect limits indicated in UI

- resources/lib/widgets.py
This was causing issues if called from the "Custom widgets" menu, and possibly slowing down the processing time of other widgets
> Move inprogress call into relevant if block

- resources/lib/item_functions.py
setting `list_item.setCast()` to an empty list appears to be throwing the sort methods for a loop.  Only set the cast when they actually exist (we're getting an empty list for music tracks)
Fixes #79
> Only set the cast if they exist

- resources/lib/downloadutils.py
- resources/lib/functions.py
- resources/lib/server_detect.py
- resources/lib/utils.py
- resources/settings.xml
- service.py
Stop storing user passwords in plain text.  Change some of the user flow to be smoother, but a lot of it is too tightly tied to network functions and needs to wait until that refactor happens.  Will force users to re-authenticate when released because the migration path in code would be super ugly.  Also possibly fixes an issue with using multiple users not authenticating properly
> Rework user data storage

- resources/lib/play_utils.py
> Don't throw errors when non-JellyCon content is playing

- resources/lib/server_detect.py
If there are no saved credentials this forces login.  Fixes a migration issue after #119
> Force login if no saved credentials

- resources/lib/widgets.py
Fixes #140 - encoding issue when updating content from the server and the `simple_new_content_check` setting is turned off
> Fix content update checks

- resources/lib/jellyfin.py
During initial login some background tasks are failing because the API class is being initialized before the setup wizard has completed and populated settings
> Ensure server is present in API requests

- resources/language/resource.language.en_gb/strings.po
- resources/lib/dialogs.py
- resources/lib/server_detect.py
- resources/skins/default/720p/QuickConnectDialog.xml
Fixes #146.  Defaults to using quick connect if it's enabled on the server with a fallback option to the old manual wizard selection if it fails or times out.
Note: Requires server version 10.8 or greater.  Does not work with the quick connect implementation in 10.7
> Add quick connect authentication

- resources/lib/menu_functions.py
Move dict definitions into a single action instead of defining a dict and then populating it one at a time.  Should be marginally more efficient, but also just cleaner to look at
> Simplify url param dict definitions

- resources/lib/server_detect.py
This quick connect implementation only works in 10.8 or newer, so account for the response from 10.7
> Make sure manual login shows when connecting to a 10.7 server

- resources/lib/play_utils.py
- resources/lib/utils.py
Fixes #175, since the server guys are jerks and broke my language specific download endpoints.
Kinda gross, since we have to download all external subs for a given video even if they're not going to be used, but trying to pass in `plugin://plugin.video.jellycon` as a subtitle endpoint won't work and gives a subtitle parser error.
> Download all external subs when playback starts

- resources/language/resource.language.en_gb/strings.po
- resources/lib/menu_functions.py
My attempt to solve https://github.com/jellyfin/jellycon/issues/19
i'm using https://api.jellyfin.org/#operation/GetResumeItems to get continue watching list
it would be nice if this feature could make it way to `Custom Widgets` too
> Add Continue Watching Widget

- resources/lib/server_detect.py
Fixes #191.  When switching to a cached user, use the cached credentials first.
> Don't error when switching to a cached user

- resources/lib/dir_functions.py
If the `show_empty_folders` option is disabled, exclude "missing" content from the api request to the server when getting the seasons list of a show.  Possible alternative method to #197, seems to achieve the same result while reducing local device load. @aiosk does this solve the issue?
side note: I don't like doing string addition like this, but I don't want to go through and rewrite all of them in this file in a bugfix PR.
> Don't request empty folders from api if setting is disabled

- resources/lib/jellyfin.py
- service.py
Fixes #209.  Another side effect where requests were using the wrong metadata and applying watched status to the previously selected user.
> Apply watched status to the correct user

- resources/language/resource.language.en_gb/strings.po
This setting didn't have any units, so it was unclear if it was in seconds or minutes
> Make it clear that the play next episode setting is in seconds

- resources/lib/utils.py
`requests.get` when download subtitle file do not respect "Verify HTTPS certificate" setting.
STEPS TO REPRODUCE:
- i have installed self sign certificate on jellyfin server
- i have set "Verify HTTPS certificate" to false on addon setting
EXPECTED RESULTS:
i can play movies
ACTUAL RESULTS:
i can not play movies.
this happened because `requests.get` when download subtitle file do not respect "Verify HTTPS certificate" setting.
this PR add "Verify HTTPS certificate" setting when downloading subtitle file
> subtitle not working on self sign certificate

- resources/lib/menu_functions.py
This adds the item limit to the list of parameters when querying recently added movies.
Fixes https://github.com/jellyfin/jellycon/issues/243
> Add item limit to the list of parameters for recently added movies

- resources/language/resource.language.en_gb/strings.po
- resources/lib/functions.py
- resources/lib/play_utils.py
- resources/settings.xml
More improvements for #128 
* Adds ability to start an Instant Mix from a song, album, or artist
* Adds ability to shuffle play an artist/album
* Fixes playback order when selecting "Play All" on an item
* Implement a max queue size.  Useful for low power devices and large music collections.
> Add instant mix and shuffle features for music

- resources/lib/play_utils.py
Start playing the first item in a queue immediately before processing the rest of the items.  Very useful for large queues of items.
> Start playing multiple items faster

- resources/lib/play_utils.py
- resources/lib/utils.py
- resources/settings.xml
Use enum for setting max bitrate, same as in jellyfin-kodi. New default is 1000000.
Fixes #257
> Increase maximum stream bitrate

- resources/lib/functions.py
- resources/lib/loghandler.py
- resources/lib/monitors.py
- resources/lib/server_sessions.py
- resources/lib/skin_cloner.py
- resources/lib/tracking.py
- resources/lib/utils.py
- resources/lib/websocket_client.py
- resources/lib/widgets.py
* Bring line lengths under 80 characters
* Standardizes on `.format()` string manipulations instead of a mixture of `.format()` and `%s`
* Fixes a few typos/mis-spellings
* Removes unused function
* Changes some long if operator chains to `if 'thing' in ['option1', 'option2', 'etc']`
> pep8 refactor - part 1

- resources/lib/play_utils.py
When using ersatz, this would cause the encoding session to never stop and hold onto those system resources forever
> Include LiveStreamId in session stopped api call

- resources/lib/functions.py
It wasn't possible to delete items from the context menu in JellyCon before, due to what was seemingly a typo.
In the code, we want to fetch the information on the video first to populate an "Are you sure?" dialog to the user. However, it uses the `DELETE` HTTP method instead of `GET`, so `item` was `None` which led to an exception.
This replaced `DELETE` with `GET`, which now correctly fetched the information of the media, and follows up with the appropriate dialog. Upon pressing **Yes**, the media is correctly deleted from the media server, and the list refreshes to reflect the removed item.
On the side, I also address a formatting issue in the delete dialog, where spacing is inconsistent around hyphens.
* Closes https://github.com/jellyfin/jellycon/issues/288
> Navigating a show and …
> fix: delete item via context menu

- resources/lib/play_utils.py
**Steps**
- Open Jellycon
- Go to shows / tvshows items, either
- `Jellyfin Libraries` > `Shows` > `Shows - Show All`
- `Global Lists` > `TV Shows` > `Tv Shows - Show All`
- Open `context menu` on series item, select `shuffle`
**Expected Result**
jellycon shuffle series episodes
**Actual Result**
jellycon not doing anything
> fix shuffle on series item context menu

- .gitignore
- build.py
Many Python developers use [venv](https://docs.python.org/3/library/venv.html) to manage their environment. Would it be fine to commit these config changes to the repo?
* Initially part of https://github.com/jellyfin/jellycon/pull/293
> chore: ignore venv in git and build

- resources/language/resource.language.en_gb/strings.po
- resources/lib/menu_functions.py
- resources/settings.xml
Introduces a new setting called **Interface Mode**. I wasn't sure where the best place to keep it was, so I put it under **Interface** → **Interaction**.
When the **Interface Mode** is set to **Simple**, it reduces the number of menus the user sees, closely resembling the web app and Jellyfin Media Player.
When a user launches Jellyfin, they're taken straight to their libraries, and when a user accessing a library, they see all media in the library with no intermediate menus.
The only exceptions are:
* `homevideos`
* `livetv`
I do not use these myself, but reviewing the contents of these menus, these submenus might be considered valuable. Especially in the case of `livetv`, skipping the intermediate menu may impede usage?
Criticism is welcome. :+1: 
* Closes …
> feat: add simple mode for less menus

- resources/language/resource.language.en_gb/strings.po
- resources/lib/widgets.py
- resources/settings.xml
Adds support for [SenorSmartyPants](https://github.com/SenorSmartyPants) rewatch feature to the episode NextUp widget.
See https://github.com/jellyfin/jellyfin/pull/7253 for server side implementation.
> Add rewatch feature to episode NextUp widget

- resources/language/resource.language.en_gb/strings.po
- resources/lib/play_utils.py
- resources/settings.xml
This adds av1 to the list of codecs that can be set to always force transcode in the settings. I tested this on the latest stable Kodi build and it works as expected.
> Add 'Force transcode av1' setting

- resources/lib/play_utils.py
Before the change we had resume position display like :
After the change we'll have :
Which is also the format kodi (at least default skin) uses.
> nicer and kodi's style resume position on resume dialog

- resources/language/resource.language.en_gb/strings.po
- resources/lib/menu_functions.py
- resources/lib/utils.py
- resources/settings.xml
As a new user the number count at the end of "Next Up (20)" kept me thinking the list contains 20 items while it is a const regardless of the content (which can be nice idea to implement).
So i added a setting option that allow the user to hide , so users who wants to keep it, can have the old behavior (I personally think it should be hidden as default)
While implementing the settings the logic of adding the item count at the end of the menu item was scattered at many places (with some place using simple concatenation and other places using format) i added a function under utils that handles the settings and visual logic at just one place.
New setting (default is "off"):
Default view :
With new setting turned "on" :
> Add setting option to hide item count limit on menu entries

- resources/lib/widgets.py
https://github.com/jellyfin/jellyfin/pull/10200 added "in progress" episodes to NextUp api query.
This change only affects jellyfin 10.9.X.
When using jellycon with jellyfin 10.9.x we now see the in progress episodes twice. 
While we can undo the work done on https://github.com/jellyfin/jellycon/pull/82 , I think its better to just pass the new parameter to NextUp query with the value of false.
This way jellycon works fine (no duplicates) on both jellyfin 10.9 and older ones.
> Explicitly request non resumeable episodes on next up widget

- resources/lib/functions.py
youtube addon maintainer says RunPlugin is an invalid way to call the addon.
So changed the call to use PlayMedia
More info on https://github.com/anxdpanic/plugin.video.youtube/issues/937
Tested on latest and older youtube addon version , trailer playback is working fine.
> Fix youtube addon call for trailer playback

- resources/language/resource.language.en_gb/strings.po
- resources/lib/dir_functions.py
- resources/lib/menu_functions.py
This new view helps on cases such as 
For example, We have 20 tv shows on our jellyfin setup.
4 are totally watched (all episodes are marked as watched)
6 are partially watched (some episodes of the shows are watched and some are not)
10 we never watched any episodes , all episodes are not watched.
This PR add the option to see only the 10 shows we never watched named "Tv Shows - Totally Unwatched".
The existing menu named "TV Shows - Unwatched" will show 16 shows (both partially watched and unwatched)
> New Tv Shows menu entry , Totally unwatched Tv Shows entries

- resources/lib/play_utils.py
The functionality to play the next episode without a prompt has been removed in [this commit](https://github.com/jellyfin/jellycon/commit/2e9a76d0dbbf6485fe2902d3b8abb31e471d0302). It seems that it was not intentional, as the setting "Prompt before play" was not removed, and disabling this now has the same effect for the user as setting "Play next episode after %" to 100, so it basically disables the play next episode feature.
This restores the possibility of playing the next episode without a prompt.
> Restore play next without prompt functionality

- .github/workflows/codeql.yaml
- .github/workflows/test.yaml
Python 2 testing has been broken for a while, and is old and horrible anyway.  Remove it from the CI to stop getting failed run emails.
Remove python2 and kodi <19 from publishing in next major release
> Remove py2 from testing CI

- resources/lib/play_utils.py
- resources/lib/utils.py
Fixes a bug when multiple external subtitle files in the same language are provided (only the last one appears).
> Fix bug with multiple external subtitles in the same languages

- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.fr/strings.po
- resources/lib/dialogs.py
- resources/lib/intro_skipper.py
- resources/lib/intro_skipper_utils.py
- resources/lib/play_utils.py
- resources/lib/utils.py
- resources/settings.xml
- resources/skins/default/720p/SkipDialog.xml
- service.py
Hello,
For my personal use I've implemented segment skip ability on jellycon.
This is my first time developping in python (let alone kodi extensions) so I probably did not take the right approach though it runs fine on my shield.
Feel free to make feedbacks.
> Add segment skip ability
