- addon.xml
- resources/lib/cache_images.py
- resources/lib/downloadutils.py
- resources/lib/image_server.py
- resources/lib/server_detect.py
As far as I can tell, nothing is broken. Tested the caching & download speed testing as well as general addon use and everything seems okay
> Replace httplib with requests

- resources/lib/loghandler.py
Fixes the logs so it's not always outputting debug logs, only when the debug setting is flipped on in the settings.  Also properly fixes the log filtering to not display the server URL.
> Fix log levels

- resources/lib/action_menu.py
- resources/lib/bitrate_dialog.py
- resources/lib/cache_images.py
- resources/lib/clientinfo.py
- resources/lib/datamanager.py
- resources/lib/dir_functions.py
- resources/lib/downloadutils.py
- resources/lib/functions.py
- resources/lib/image_server.py
- resources/lib/item_functions.py
- resources/lib/jsonrpc.py
- resources/lib/kodi_utils.py
- resources/lib/library_change_monitor.py
- resources/lib/menu_functions.py
- resources/lib/picture_viewer.py
- resources/lib/play_utils.py
- resources/lib/playnext.py
- resources/lib/resume_dialog.py
- resources/lib/safe_delete_dialog.py
- resources/lib/server_detect.py
- resources/lib/server_sessions.py
- resources/lib/skin_cloner.py
- resources/lib/tracking.py
- resources/lib/trakttokodi.py
- resources/lib/translation.py
- resources/lib/utils.py
- resources/lib/websocket.py
- resources/lib/widgets.py
+ few minor changes.
Fixes #18 and probably fixes #21
> Use future strings to fix unicode errors

- resources/lib/downloadutils.py
- resources/lib/server_detect.py
> Connect to servers with special characters in the name

- resources/lib/datamanager.py
- resources/lib/downloadutils.py
- resources/lib/functions.py
- resources/lib/item_functions.py
- resources/lib/menu_functions.py
- resources/lib/server_detect.py
- resources/lib/server_sessions.py
- resources/lib/utils.py
- resources/lib/widgets.py
Parse the json from the api in the download function instead of calling `json.loads()` in multiple places
> Proper API json parsing

- resources/lib/downloadutils.py
- resources/lib/play_utils.py
- resources/lib/server_detect.py
- resources/lib/utils.py
- resources/lib/widgets.py
Fixes any issues I found on a 10.7 RC1 server, along with a few unrelated but needed changes.
- Use `/system/info/public` as a test URL instead of the users list
- Don't error on empty user list (they could all be hidden)
- Use proper json payload for authentication instead of a urlencoded form
- When playback stops, only try to delete the transcode in the server if we're actually transcoding
Edit: Fixes #20
> 10.7 fixes

- resources/lib/downloadutils.py
> Don't urlencode auth json payload

- resources/lib/play_utils.py
> Show proper language names for external subs

- resources/lib/context_monitor.py
- resources/lib/play_utils.py
- resources/lib/websocket_client.py
> Use future imports for all library files

- resources/lib/functions.py
- resources/lib/server_detect.py
Kodi 19 changes the yes/no dialog boxes to only have one message, so we need to combine strings on these.
> Fix yes/no dialogs in kodi 19

- resources/lib/image_server.py
- resources/lib/menu_functions.py
> Fix browsing by pages

- resources/lib/server_detect.py
Ref: https://www.reddit.com/r/jellyfin/comments/m0ovht/how_to_add_jellycon_to_kodi_home_screen/guhycgz/
> Fix displaying public user list

- resources/lib/play_utils.py
> Include position ticks in external sub call

- resources/lib/play_utils.py
- resources/lib/playnext.py
- resources/lib/utils.py
- service.py
> Fix next episode dialog

- resources/lib/play_utils.py
> Properly report stopped playback to the server

- resources/lib/cache_images.py
- resources/lib/utils.py
> Fix image caching

- resources/lib/play_utils.py
Fixes an issue where reporting to the server would always say the last item in a playlist was playing
> Report tracks correctly when a playlist is playing

- resources/lib/play_utils.py
Fixes #69.  again.  I don't like relying on the HomeWindow as a variable store, but until things get refactored into classes and centralized it seems the best option available.
> Fix stopped playback reporting

- default.py
- resources/lib/action_menu.py
- resources/lib/cache_images.py
- resources/lib/datamanager.py
- resources/lib/dialogs.py
- resources/lib/dir_functions.py
- resources/lib/functions.py
- resources/lib/image_server.py
- resources/lib/item_functions.py
- resources/lib/jellyfin.py
- resources/lib/kodi_utils.py
- resources/lib/lazylogger.py
- resources/lib/loghandler.py
- resources/lib/menu_functions.py
- resources/lib/monitors.py
- resources/lib/picture_viewer.py
- resources/lib/play_utils.py
- resources/lib/playnext.py
- resources/lib/server_detect.py
- resources/lib/server_sessions.py
- resources/lib/skin_cloner.py
- resources/lib/tracking.py
- resources/lib/trakttokodi.py
- resources/lib/utils.py
- resources/lib/websocket_client.py
- resources/lib/widgets.py
- service.py
> Copy translate_path from Jf4Kodi, fix LazyLogger

- resources/lib/jellyfin.py
Fixes #108.  In theory.  I haven't tested, but it should fix it.
> Make requests respect the verify certificate setting

- resources/lib/widgets.py
- resources/settings.xml
> Make widgets respect episode name format setting

- resources/lib/menu_functions.py
> Fallback to empty lists instead of failing

- resources/lib/jellyfin.py
The server portion of the post_capabilities URL was being added twice and erroring out
> Fix remote control

- resources/lib/widgets.py
> Fix movie recommendations

- resources/lib/item_functions.py
- resources/lib/utils.py
Fixes timezone, percentage calculation, and string formatting so the menu will load properly
> Fix browsing the Live TV programs menu

- resources/lib/play_utils.py
Fixes #28 (With EratzTV at least, I can't test any other methods)
> Fix live tv playback

- resources/lib/menu_functions.py
- resources/lib/play_utils.py
Allow live tv to direct stream instead of transcoding it all the time.  Also fixes a metadata issue where channel info was missing.
> Rework live tv playback

- resources/lib/dir_functions.py
Skin shortcuts from before the network rework had a different format.  This helps to translate between them
> Fix legacy skin shortcuts

- resources/lib/jellyfin.py
- resources/lib/menu_functions.py
- resources/lib/utils.py
- resources/lib/widgets.py
> Fix stale data after storage migration

- resources/lib/play_utils.py
Fixes #142, found by @baconsalad
> Fix errors when stopping transcoded playback

- resources/language/resource.language.en_gb/strings.po
- resources/lib/functions.py
- resources/lib/menu_functions.py
> Add genres and alpha picker to music

- resources/lib/menu_functions.py
* Combines sequential for loops into a single loop
* Reuse URL parameter dicts instead of rebuilding them from scratch for every entry
> Optimize loops while building menus

- resources/lib/functions.py
- service.py
This appears to be related to an old emby plugin that was never brought over to JF land.
> Remove safe delete code

- resources/lib/functions.py
- resources/lib/item_functions.py
- resources/lib/kodi_utils.py
- resources/lib/widgets.py
Should speed up list generation.  Taken from https://forum.kodi.tv/showthread.php?tid=329315
Also removes the check for Kodi 17
> Use offscreen option when generating all listitems

- resources/lib/play_utils.py
> Allow playback from Info menu

- resources/lib/functions.py
Likely been broken since the py3/kodi 19 migration
> Fix performance profiling

- resources/lib/jellyfin.py
Especially on low power devices, using `requests` built in json decoder is significantly slower than just parsing the string ourselves.  From tests I did on a Pi3 with an API call to the server that returns ~700 movies:
* Using `response.json()` - 0.9872016906738281 seconds
* Using `json.loads(response.text)` - 0.0701589584350586 seconds
It seems like back in the py2 days, `simplejson` (preferred under the hood by `requests`) used to be faster than the builtin `json` library, but that's clearly no longer the case in py3.
Special shout out to @faush01 for inspiring a rabbit hole of testing.
> Manually decode json responses

- resources/lib/play_utils.py
Fixes #188 .  Don't know why I didn't run into it in my testing, but definitely showing up now.
> Fix sys.argv comparison

- resources/lib/play_utils.py
> Ensure a handle is valid before trying to use it to start playback

- resources/lib/jellyfin.py
- resources/lib/server_detect.py
- resources/lib/utils.py
> Fix user switching

- resources/lib/play_utils.py
> Fix playing livetv from tvheadend

- resources/lib/utils.py
> Force unique client IDs when using quick connect

- resources/lib/dir_functions.py
- resources/lib/menu_functions.py
Fixes issues where the menus reference the wrong user's metadata after switching users.  In theory will fix #215
> Fix stale menu links when user switching

- resources/lib/server_detect.py
- resources/lib/utils.py
If you've logged in as a user on a device, chances are you'll want to again, so display saved user if they aren't in the public list.
> Show saved users in the user selection list

- resources/lib/dir_functions.py
- resources/lib/menu_functions.py
> Add support for mixed content libraries

- resources/lib/play_utils.py
This is a remnant from the old network handler code and is not longer used
> Cleanup old https verify method

- resources/lib/server_detect.py
> Initialize variable before it's used

- resources/lib/play_utils.py
Ref: https://github.com/MoojMidge/service.upnext/issues/16
> Fix support for the upnext addon

- resources/lib/item_functions.py
I don't know why this fixes it, but i don't actually care.
Fixes #269
> Fix context menu in kodi v20

- resources/lib/utils.py
Fixes the integration with the upnext addon.  Again.
Fixes #273
> Fix the formatting of the upnext notification

- .github/workflows/codeql.yaml
- .github/workflows/test.yaml
https://github.com/actions/setup-python/issues/672#issuecomment-1607332070
Replicated from the jellyfin-kodi repo
https://github.com/jellyfin/jellyfin-kodi/commit/5c5b1d14cb1bf1ebf557337763f87e302c12b8a2
> Fix python2.7 Action workflows

- service.py
While looking at the code , found a duplicate line of code, tested it locally after removal , all works fine.
> Remove duplicate line of code
